# Generated by Django 4.0.3 on 2023-01-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdata', '0002_contact_desc_contact_email_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
