# Generated by Django 4.0.3 on 2023-01-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopdata', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userlogin',
        ),
    ]
