# Generated by Django 4.0.3 on 2023-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdata', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
