# Generated by Django 4.1.7 on 2023-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdata', '0009_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
